# Hexo配置
## 文档：https://hexo.io/docs/configuration.html
## 来源：https://github.com/hexojs/hexo/

# 站点
title:  # 网站标题
subtitle: '' # 网站副标题
description: '' # 网站描述
keywords:   # 网站的关键词
author:  # 您的名字
language: zh-CN # 网站语言
timezone: '' # 网站时区

# 网址
url: http://example.com # 在此处设置您的网站网址
permalink: :year/:month/:day/:title/ # 文章的永久链接格式
permalink_defaults:
pretty_urls:
  trailing_index: true # 设置为 false 以从永久链接中删除尾随的“index.html”
  trailing_html: true # 设置为 false 以从永久链接中删除尾随的“.html”

# 目录
source_dir: source # 资源文件夹
public_dir: public # 生成的站点文件
tag_dir: tags # 生成的站点文件
archive_dir: archives # 归档文件夹
category_dir: categories # 分类文件夹
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 文章
new_post_name: :title.md # 新文章的文件名称
default_layout: post # 预设布局
titlecase: false # 将标题转换为标题大小写
external_link:
  enable: true # 在新标签页中打开外部链接
  field: site # 整个网站（site）生效/仅对文章（post）生效
  exclude: ''
filename_case: 0 # 把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false # 显示草稿
post_asset_folder: false # 启动 Asset 文件夹
relative_link: false # 把链接改为与根目录的相对位址
future: true # 显示未来的文章
highlight: # 代码块的设置, 请参考 Highlight.js 进行设置
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# 首页设置
# path：博客索引页的根路径。（默认值 = ''）
# per_page：每页显示的帖子数。（0 = 禁用分页）
# order_by：Posts order（默认按日期降序排序）
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 类别和标签
default_category: uncategorized
category_map:
tag_map:

# 元数据元素
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# 日期/时间格式
# Hexo 使用 Moment.js 来解析和显示日期
# 您可以自定义 中定义的日期格式
# http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option 支持 'mtime'， 'date'， 'empty'
updated_option: 'mtime'

# 分页
## 将per_page设置为 0 来禁用分页
per_page: 10
pagination_dir: page

# 包含/排除文件
## include：/exclude：选项仅适用于“源/”文件夹
include:
exclude:
ignore:

# 扩展
# 插件：https://hexo.io/plugins/
# 主题：https://hexo.io/themes/
theme:  # 主题

# 部署
# 文档：https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
